// examples/nuxt/app/pages/sensitive-info/submitted.vue
<template>
  <main class="page">
    <section class="section">
      <h1 class="heading-primary">Form submitted</h1>
      <p class="typography-primary">
        If this were a real form, your message would have been submitted.
      </p>
    </section>
    <hr class="divider" />
    <WhatNext />
  </main>
</template>

// examples/nextjs-fly/app/sensitive-info/submitted/page.tsx
import { WhatNext } from "@/components/compositions/WhatNext";

export default function IndexPage() {
  return (
    <div className="page">
      <section className="section">
        <h1 className="heading-primary">Form submitted</h1>
        <p className="typography-primary">
          If this were a real form, your message would have been submitted.
        </p>
      </section>

      <hr className="divider" />

      <WhatNext />
    </div>
  );
}
