// examples/nuxt/app/components/WhatNext.vue
<template>
  <div class="section">
    <h2 class="heading-secondary">What next?</h2>
    <div class="list-actions">
      <a href="https://app.arcjet.com" target="_blank" class="button-secondary">
        Sign up for Arcjet
      </a>
    </div>
    <div class="list-actions">
      <p class="typography-secondary">Want to know more?{{ " " }}</p>
      <div>
        <a href="https://docs.arcjet.com" target="_blank" class="link">
          Arcjet docs
        </a>
        <span class="typography-secondary"> {{ " " }}/{{ " " }} </span>
        <a
          href="https://arcjet.com/discord"
          target="_blank"
          rel="noreferrer"
          class="link"
        >
          Join our Discord
        </a>
      </div>
    </div>
  </div>
</template>

// examples/gatsby/src/components/WhatNext.tsx
import * as React from "react";

export function WhatNext() {
  return (
    <div className="section">
      <h2 className="heading-secondary">What next?</h2>
      <div className="list-actions">
        <a
          href="https://app.arcjet.com"
          target="_blank"
          rel="noopener noreferrer"
          className="button-secondary"
        >
          Sign up for Arcjet
        </a>
      </div>
      <div className="list-actions">
        <p className="typography-secondary">Want to know more? </p>
        <div>
          <a
            href="https://docs.arcjet.com"
            target="_blank"
            rel="noopener noreferrer"
            className="link"
          >
            Arcjet docs
          </a>
          <span className="typography-secondary">{" / "}</span>
          <a
            href="https://arcjet.com/discord"
            target="_blank"
            rel="noreferrer"
            className="link"
          >
            Join our Discord
          </a>
        </div>
      </div>
    </div>
  );
}
