// examples/nuxt/app/pages/sensitive-info/submitted.vue
<template>
  <main class="page">
    <section class="section">
      <h1 class="heading-primary">Form submitted</h1>
      <p class="typography-primary">
        If this were a real form, your message would have been submitted.
      </p>
    </section>
    <hr class="divider" />
    <WhatNext />
  </main>
</template>

// examples/tanstack-start/src/routes/signup/submitted.tsx
import { createFileRoute } from "@tanstack/react-router";
import { WhatNext } from "~/components/WhatNext";

export const Route = createFileRoute("/signup/submitted")({
  component: RouteComponent,
});

function RouteComponent() {
  return (
    <main className="page">
      <section className="section">
        <h1 className="heading-primary">Form submitted</h1>
        <p className="typography-primary">
          If this were a real form, your message would have been submitted.
        </p>
      </section>
      <hr className="divider" />
      <WhatNext />
    </main>
  );
}
