// examples/sveltekit/src/routes/rate-limiting/+page.svelte
<script lang="ts">
  import { enhance } from "$app/forms";
  import WhatNext from "$lib/components/WhatNext.svelte";
  import type { PageProps } from "./$types";

  let { form }: PageProps = $props();
</script>

<main class="page">
  <div class="section">
    <h1 class="heading-primary">Arcjet rate limiting example</h1>
    <p class="typography--description">
      This page is protected by
      <a href="https://docs.arcjet.com/bot-protection/concepts" class="link"
        >Arcjet's rate limiting</a
      >.
    </p>
  </div>

  <hr class="divider" />

  <div class="section">
    <h2 class="heading-secondary">Try it</h2>
    <form class="form" id="form-rate-limit" method="POST" use:enhance>
      <button type="submit" class="button-primary form-button">Push me</button>
      {#if form?.message || form?.error}
        <pre class="code-block"><code>{form?.message ?? form?.error}</code
          ></pre>
      {/if}
    </form>

    <p>The limit is set to 2 requests every 60 seconds.</p>
    <p class="typography--subtitle">
      Rate limits can be
      <a
        href="https://docs.arcjet.com/reference/astro#ad-hoc-rules"
        class="link">dynamically adjusted</a
      >
      e.g. to set a limit based on the authenticated user.
    </p>
  </div>

  <hr class="divider" />

  <div class="section">
    <h2 class="heading-secondary">See the code</h2>
    <p class="typography--subtitle">
      The
      <a
        href="https://github.com/arcjet/example-sveltekit/blob/main/src/routes/rate-limiting/+page.server.ts"
        target="_blank"
        rel="noreferrer"
        class="link"
      >
        form action
      </a>
      imports a
      <a
        href="https://github.com/arcjet/example-sveltekit/blob/main/src/lib/server/arcjet.ts"
        target="_blank"
        rel="noreferrer"
        class="link"
      >
        centralized Arcjet client
      </a>
      which sets base rules.
    </p>
  </div>

  <hr class="divider" />

  <WhatNext />
</main>

// examples/nextjs/app/rate-limiting/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { WhatNext } from "@/components/compositions/WhatNext";
import { RLForm } from "@/components/RLForm";

export const metadata: Metadata = {
  title: "Rate limiting example",
  description: "An example of Arcjet's rate limiting for Next.js.",
};

export default async function IndexPage() {
  return (
    <main className="page">
      <div className="section">
        <h1 className="heading-primary">Arcjet rate limiting example</h1>
        <p className="typography--description">
          This page is protected by{" "}
          <Link
            href="https://docs.arcjet.com/bot-protection/concepts"
            className="link"
          >
            Arcjet&apos;s rate limiting
          </Link>
          .
        </p>
      </div>

      <hr className="divider" />

      <div className="section">
        <h2 className="heading-secondary">Try it</h2>
        <RLForm />

        <p>The limit is set to 2 requests every 60 seconds.</p>
        <p className="typography--subtitle">
          Rate limits can be{" "}
          <Link
            href="https://docs.arcjet.com/reference/nextjs#ad-hoc-rules"
            className="link"
          >
            dynamically adjusted
          </Link>{" "}
          e.g. to set a limit based on the authenticated user.
        </p>
      </div>

      <hr className="divider" />

      <div className="section">
        <h2 className="heading-secondary">See the code</h2>
        <p className="typography--subtitle">
          The{" "}
          <Link
            href="https://github.com/arcjet/example-nextjs/blob/main/app/rate-limiting/test/route.ts"
            target="_blank"
            rel="noreferrer"
            className="link"
          >
            API route
          </Link>{" "}
          imports a{" "}
          <Link
            href="https://github.com/arcjet/example-nextjs/blob/main/lib/arcjet.ts"
            target="_blank"
            rel="noreferrer"
            className="link"
          >
            centralized Arcjet client
          </Link>{" "}
          which sets base rules.
        </p>
      </div>

      <hr className="divider" />

      <WhatNext />
    </main>
  );
}
