// examples/nextjs-fly/app/sensitive-info/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { WhatNext } from "@/components/compositions/WhatNext";
import { SupportForm } from "@/components/SupportForm";

export const metadata: Metadata = {
  title: "Sensitive info detection example",
  description:
    "An example of Arcjet's sensitive info detection for Next.js. Detect credit card numbers and other PII with Next.js.",
};

export default function IndexPage() {
  return (
    <main className="page">
      <div className="section">
        <h1 className="heading-primary">
          Arcjet sensitive info detection example
        </h1>
        <p className="typography-primary">
          This form uses{" "}
          <Link
            href="https://docs.arcjet.com/sensitive-info/concepts"
            className="link"
          >
            Arcjet&apos;s sensitive info detection
          </Link>{" "}
          feature which is configured to detect credit card numbers. It can be
          configured to detect other types of sensitive information and custom
          patterns.
        </p>
        <p className="typography-secondary">
          The request is analyzed entirely on your server so no sensitive
          information is sent to Arcjet.
        </p>
      </div>

      <hr className="divider" />

      <div className="section">
        <h2 className="heading-secondary">Try it</h2>

        <SupportForm />
      </div>

      <hr className="divider" />

      <div className="section">
        <h2 className="heading-secondary">See the code</h2>
        <p className="typography-secondary">
          The{" "}
          <Link
            href="https://github.com/arcjet/example-nextjs-fly/blob/main/app/sensitive-info/test/route.ts"
            target="_blank"
            rel="noreferrer"
            className="link"
          >
            API route
          </Link>{" "}
          imports a{" "}
          <Link
            href="https://github.com/arcjet/example-nextjs-fly/blob/main/lib/arcjet.ts"
            target="_blank"
            rel="noreferrer"
            className="link"
          >
            centralized Arcjet client
          </Link>{" "}
          which sets base rules.
        </p>
      </div>

      <hr className="divider" />

      <WhatNext />
    </main>
  );
}

// examples/sveltekit/src/routes/sensitive-info/+page.svelte
<script lang="ts">
  import { enhance } from "$app/forms";
  import WhatNext from "$lib/components/WhatNext.svelte";
  import type { PageProps } from "./$types";

  let { form }: PageProps = $props();
</script>

<main class="page">
  <div class="section">
    <h1 class="heading-primary">Arcjet sensitive info detection example</h1>
    <p class="typography-primary">
      This form uses
      <a href="https://docs.arcjet.com/sensitive-info/concepts" class="link"
        >Arcjet's sensitive info detection</a
      >
      feature which is configured to detect credit card numbers. It can be configured
      to detect other types of sensitive information and custom patterns.
    </p>
    <p class="typography-secondary">
      The request is analyzed entirely on your server so no sensitive
      information is sent to Arcjet.
    </p>
  </div>

  <hr class="divider" />

  <div class="section">
    <h2 class="heading-secondary">Try it</h2>

    <form class="form" id="form-sensitive-info" method="POST" use:enhance>
      <div class="form-field">
        <label class="form-label">
          Message
          <textarea
            placeholder="Please enter your message."
            class="form-textarea"
            name="supportMessage"
            >{"I ordered a hat from your store and would like to request a refund. My credit card number is 4111111111111111"}</textarea
          >
        </label>
        {#if form?.error}
          <p class="form-error">{form.error}</p>
        {/if}
      </div>
      <button type="submit" class="button-primary form-button">Submit</button>
    </form>
  </div>

  <hr class="divider" />

  <div class="section">
    <h2 class="heading-secondary">See the code</h2>
    <p class="typography-secondary">
      The
      <a
        href="https://github.com/arcjet/example-sveltekit/blob/main/src/routes/sensitive-info/+page.server.ts"
        target="_blank"
        rel="noreferrer"
        class="link"
      >
        form action
      </a>
      imports a
      <a
        href="https://github.com/arcjet/example-sveltekit/blob/main/src/lib/server/arcjet.ts"
        target="_blank"
        rel="noreferrer"
        class="link"
      >
        centralized Arcjet client
      </a>
      which sets base rules.
    </p>
  </div>

  <hr class="divider" />

  <WhatNext />
</main>
